<?php
return [
    [
        'title' => 'MARVEL-API-CLIENT',
        'description' => 'PHP Client for the Marvel API',
        'github' => 'marvel-api-client',
        'packagist' => 'marvel-api-client',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SLIM-OAUTH2',
        'description' => 'A collection of OAuth2 routes, middleware and utilities for use within a Slim Framework API',
        'github' => 'slim-oauth2',
        'packagist' => 'slim-oauth2',
        'scrutinizer' => false,
        'coverage' => false,
    ],
    [
        'title' => 'SLIM-OAUTH2-HTTP',
        'description' => 'Bridge components for slim and oauth2 http messages.',
        'github' => 'slim-oauth2-http',
        'packagist' => 'slim-oauth2-http',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SLIM-OAUTH2-MIDDLEWARE',
        'description' => 'OAuth2 middleware for use within a Slim Framework API',
        'github' => 'slim-oauth2-middleware',
        'packagist' => 'slim-oauth2-middleware',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SLIM-OAUTH2-ROUTES',
        'description' => 'OAuth2 routes for use within a Slim Framework API',
        'github' => 'slim-oauth2-routes',
        'packagist' => 'slim-oauth2-routes',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SPL-Exceptions',
        'description' => 'Collection of standard exception classes',
        'github' => 'spl-exceptions-php',
        'packagist' => 'spl-exceptions',
        'scrutinizer' => false,
        'coverage' => false,
    ],
    [
        'title' => 'Util-Exceptions',
        'description' => 'Collection of exception utility classes',
        'github' => 'util-exceptions-php',
        'packagist' => 'util-exceptions',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'Test Helpers',
        'description' => 'Classes designed to assist with PHPUnit testing',
        'github' => 'test-helpers',
        'packagist' => 'test-helpers',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'Date',
        'description' => 'DateTime utilities and classes',
        'github' => 'date-php',
        'packagist' => 'date',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'DOM',
        'description' => 'Collection of DOMDocument utilities',
        'github' => 'dom-php',
        'packagist' => 'dom',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SPL-Types',
        'description' => 'A collection of classes which provide various typehandling.',
        'github' => 'spl-types-php',
        'packagist' => 'spl-types',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'SPL-DataStructures',
        'description' => 'A set of standard datastructures.',
        'github' => 'spl-datastructures-php',
        'packagist' => 'spl-datastructures',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'Encapsules',
        'description' => 'A collection of small wrapper classes which encapsulates behavior with primitive types and strings.',
        'github' => 'encapsules',
        'packagist' => 'encapsules',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'IO',
        'description' => 'Collection of PHP classes to work with file systems',
        'github' => 'io-php',
        'packagist' => 'io',
        'scrutinizer' => true,
        'coverage' => true,
    ],
    [
        'title' => 'CSV',
        'description' => 'Collection of classes to work with csv files',
        'github' => 'csv-php',
        'packagist' => 'csv',
        'scrutinizer' => true,
        'coverage' => true,
    ],
];
